### ISSUE TITLE
Migration error: The current CSharpHelper cannot scaffold literals of type 'EFCore.TimeTraveler.TemporalTables'.

### ISSUE THREAD

**Issue by allyassist** [VantageSoftware/EFCore.TimeTraveler#6]
As per instructions in the main README.md, I tried to enable temporal querying on one entity:

`modelBuilder.Entity<InterpolationVariable>().EnableTemporalQuery();`

I moved it to the end of OnModelCreating() as per comments in `EFCore.TimeTraveler/Extensions.cs`

Note that all entities have temporal tables enabled by a ***later*** migration. The problem occurs in the initial migration. The method used is shown in https://www.eidias.com/blog/2018/8/29/using-sql-temporal-tables-with-entity-framework-core , which probably does not matter since it has not yet been invoked by the migration runner.

Here is the migration command and its stack dump (Entity Framework Core .NET Command-line Tools 3.1.2):

```
% dotnet ef migrations add initial -o ./Migrations
Build started...
Build succeeded.
System.InvalidOperationException: The current CSharpHelper cannot scaffold literals of type 'EFCore.TimeTraveler.TemporalTables'. Configure your services to use one that can.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotation(IAnnotation annotation, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotations(IReadOnlyList`1 annotations, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The current CSharpHelper cannot scaffold literals of type 'EFCore.TimeTraveler.TemporalTables'. Configure your services to use one that can.
```

**Comment by bbrandt** [comment]
Hi @allyassist ,

Thank you for logging an issue.  

Please review issue #5 and #3 to see if there is anything there that can help you.  If you don't get it worked out after that, then please submit a small test project that is able to reproduce the issue.  

I also recommend checking out the https://github.com/Adam-Langley/efcore-temporal-query library as that is likely a better option.
